[tool.poetry]
name = "souris-gui-test"
version = "0.1.0"
description = "Test gui for souris app"
authors = ["MooSee2 <52461645+MooSee2@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "==3.9.12"
dash = "^2.14.2"
loguru = "^0.7.2"
python-dotenv = "^1.0.1"
pandas = "^2.2.0"
dash-bootstrap-components = "^1.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 999
